[cursor.style]
blinking = "Always"
shape = "Underline"

[env]
TERM = "xterm-256color"

[font]
size = 16

[font.bold]
style = "SemiBold"

[font.normal]
family = "Inconsolata"
style = "Regular"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mode = "~Vi"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "SearchForward"
key = "F"
mode = "~Search"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "SearchBackward"
key = "B"
mode = "~Search"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Plus"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Control"

[[keyboard.bindings]]
command = { program = "alacritty", args = ["msg", "config", "window.opacity=1.0"] }
key = "O"
mods = "Control|Shift"

[[keyboard.bindings]]
command = { program = "alacritty", args = ["msg", "config", "-r"] }
key = "R"
mods = "Control|Shift"

[terminal.shell]
program = "/usr/bin/fish"

[general]
import = ["~/.config/alacritty/base16_default_darker.toml"]

[window]
opacity = 0.75

[window.padding]
x = 24
y = 16

[terminal]
